version: '3.8'

# Workflow
services:
  app:
    build:
      context: .
      dockerfile: compose/node/Dockerfile
    ports:
      - "3030:8080"
    volumes:
      - "./:/app"
    networks:
      - sberhealth

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9080:80"
    volumes:
      - ./dist:/app
      - ./compose/nginx:/etc/nginx/conf.d
    networks:
      - sberhealth

  php:
    image: php:8-fpm-alpine
    expose:
      - 9000
    volumes:
    - ./dist:/app
    networks:
      - sberhealth

networks:
  sberhealth:
